CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'PK',
  email VARCHAR(320) NOT NULL UNIQUE COMMENT '사용자 이메일(유니크)',
  name VARCHAR(100) NOT NULL COMMENT '사용자 이름',
  created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
  updated_at DATETIME(6) NOT NULL COMMENT '수정 시각'
) COMMENT='사용자 기본 정보';
