package lab.coder.colly.shared.error;

public enum ErrorCode {
    USER_NOT_FOUND,
    ORDER_NOT_FOUND,
    DUPLICATE_EMAIL,
    INVALID_AMOUNT,
    POST_NOT_FOUND,
    JOIN_NOT_FOUND,
    JOIN_NOT_ALLOWED,
    JOIN_ALREADY_EXISTS,
    INVALID_POST_PAYLOAD,
    USER_RESTRICTED,
    FORBIDDEN_ACTION,
    AUTH_INVALID_EMAIL,
    MAGIC_LINK_NOT_FOUND,
    MAGIC_LINK_EXPIRED,
    MAGIC_LINK_ALREADY_USED,
    MAGIC_LINK_RATE_LIMITED
}
